# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

strategy:
 matrix:
   linux:
      os: 'ubuntu-latest'
   mac:
     os: 'mac-latest'
pool:
  vmImage: $(os)
steps:
  - script: echo this is $(os)
    displayName: 'Run a online script'